### ISSUE TITLE
Can we add the top banner to the main owi page?

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-CIDA/OWI_website#47]
![2016-09-19_15-18-02](https://cloud.githubusercontent.com/assets/1105215/18647606/4e9cac12-7e7c-11e6-8ea9-dcef30129deb.png)

**Comment by ldecicco-USGS** [comment]
directly on owi.usgs.gov

**Comment by ldecicco-USGS** [comment]
Also, (maybe already working on this)....can we get a box on that landing page for blogs? Presumably, we'll want the vizzy landing page there too. This could all happen when the vizzy landing page is done...there's no hurry what-so-ever.

Also #2 (Laura's random train of thought....) while you are working on the vizzy landing page...maybe we could use that same style for each of these boxes? ie.. people, products, partners, careers, blogs, viz lab could look have the same look as whatever you are doing with the viz lab landing page.

**Comment by mwernimont** [comment]
@ldecicco-USGS I like the idea of just adding the blogs and vizlab as blue blocks instead of adding the redundant nav bar to the owi main page, to keep the look and feel. Do we want the viz lab as a main option as the owi website?

**Comment by ldecicco-USGS** [comment]
I'd defer to @eread-usgs if we want viz lab as a main option.

**Comment by eread-usgs** [comment]
does main option mean equivalent with People Products Partners, etc? @mwernimont @ldecicco-USGS

**Comment by mwernimont** [comment]
Thats what I was thinking, or is that too forward @eread-usgs ?

**Comment by eread-usgs** [comment]
I think that would be great, just wanted to be sure I understood right.

**Comment by mwernimont** [comment]
@eread-usgs @ldecicco-USGS Should this wait until we have the vizlab page live?

**Comment by mwernimont** [comment]
@ldecicco-USGS #49 adds the blogs as a blue button to the website
