### ISSUE TITLE
datascience.html needs to migrate from CIDA site

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-CIDA/OWI_website#53]
We'd like the data science page to make its way over to OWI somehow. It should be able to be navigated to as well. That's not currenlty possible on cida.usgs.gov - you have to find it through a search or know the URL. 

http://cida.usgs.gov/datascience.html

**Comment by lindsaycarr** [comment]
@mwernimont could you handle when you might be free next?? I could give it a go if you think it's not very complicated.

**Comment by mwernimont** [comment]
yeah, it won't be until next week, but I can definitely do it.

**Comment by lindsaycarr** [comment]
Even sooner than I anticipated. Awesome, thanks!

**Comment by jkreft-usgs** [comment]
this is basically done in the cruft branch,
https://github.com/USGS-CIDA/OWI_website/blob/Cruft_R_DS_etc/owi_website/templates/datascience.html

**Comment by jkreft-usgs** [comment]
https://github.com/USGS-CIDA/OWI_website/blob/Cruft_R_DS_etc/owi_website/views.py#L19

**Comment by mwernimont** [comment]
@lindsaycarr Want to give the page a look over? http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/datascience/

If you think its up to snuff I can push it to prod, or if you got changes let me know!

**Comment by lindsaycarr** [comment]
My only thought is having the buttons and sentence introducing our "cross-functional team" above the team pics, but you are the expert designer so don't switch it if that makes it more awkward!

![image](https://cloud.githubusercontent.com/assets/13220910/21204508/785aa510-c21d-11e6-9b79-4c2f3d0c3a99.png)

**Comment by lindsaycarr** [comment]
On a similar note, how does one change their image? I have a more professional one that I use for all my other accounts. I saw that you had two versions, so I figured there are specific sizing/resolution specs I need to follow.

**Comment by mwernimont** [comment]
@lindsaycarr I can make that change for you. 

As for the picture, you can pull down the owi website repo, and go into owi_website/static/images/professional_pages and replace the photo of you with the one you want. Its easiest if you just name the new file the same as the old one so the template will just pick it up and you don't have to go messing with any other files. Make sense?

**Comment by mwernimont** [comment]
@lindsaycarr https://github.com/USGS-CIDA/OWI_website/pull/58 made the content change, give dev a look again later? Pretty sure the jenkins job ran and deployed to dev.

**Comment by lindsaycarr** [comment]
@mwernimont one last piece - can there be a space between the section header and the text? Then, it will for sure be good!

**Comment by lindsaycarr** [comment]
yay! it looks good!
