### ISSUE TITLE
Peoples schools are set as links but we don't have urls

### ISSUE THREAD

**Issue by jkreft-usgs** [USGS-CIDA/OWI_website#8]
see 

https://github.com/USGS-CIDA/OWI_website/blob/e4ffcce1a00c5a3d68969a62118bd0987500b725/owi_website/templates/person.html#L50

was that supposed to be a div or span?

**Comment by mwernimont** [comment]
Was an old hack I used that no longer needed, just need to get get of the a tag and everything should be gravy
